export { default as Css } from '../../assets/skills/css.svg'
export { default as Express } from '../../assets/skills/expressjs.svg'
export { default as Html } from '../../assets/skills/html.svg'
export { default as Java } from '../../assets/skills/java.svg'
export { default as Javascript } from '../../assets/skills/javascript.svg'
export { default as Nodejs } from '../../assets/skills/nodejs.svg'
export { default as React } from '../../assets/skills/reactjs.svg'
export { default as Tailwind } from '../../assets/skills/tailwindcss.svg'